### ISSUE TITLE
Criar Factories para iniciar com TDD

### ISSUE THREAD

**Issue by girol** [uspdev/sigtec#11]
- [x] Usuários com cargos
- [x] Salas
- [x] Tickets
- [x] Usuários com níveis de acesso

Para facilitar, depende de #13 

Níveis de acesso serão criados com o método nativo `attach()` do Eloquent

**Comment by thiagogomesverissimo** [comment]
E depois do TDD implementado pode fazer o bulid com o travis =)

**Comment by girol** [comment]
nem a pau uaheuhauehuah

**Comment by thiagogomesverissimo** [comment]
pq?

**Comment by girol** [comment]
Pq não precisa de tudo isso. Depois de pronto eu penso nisso. Se quiser fazer o setup fique à vontade.

**Comment by thiagogomesverissimo** [comment]
ok, vou deixar uma issue abera para mim.
