### ISSUE TITLE
Inserir informações sobre o sistema no readme

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/sigtec#5]
e o @girol volta a ativa!

**Comment by girol** [comment]
Na vdd to organizando os projetos. Meses sem arrumar. Vou colocar em breve o `README`

**Comment by girol** [comment]
Não pretendo integrar isso agora. Não tenho nem token o OAuth, daí cada um implementa no seu fork de sua unidade, mas vou tentar deixar agnóstico o método de autenticação e integração de libs.

**Comment by thiagogomesverissimo** [comment]
kkk sim eu sei. foi para encher seu saco

**Comment by girol** [comment]
:finnadie:
